version: '3'

services:

  vtiger:
    image: javanile/vtiger:7.1.0
    environment:
      - VT_DEBUG=true
      - MYSQL_HOST=mysql
      - MYSQL_DATABASE=vtiger
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - "18080:80"
    volumes:
      - ./:/app
      - ./volumes/logs:/var/www/html/vtiger/logs
      - ./volumes/storage:/var/www/html/vtiger/storage
    links:
      - mysql

  mysql:
    image: mysql:5.5
    environment:
      - MYSQL_DATABASE=vtiger
      - MYSQL_ROOT_PASSWORD=secret
    volumes:
      - mysql:/var/lib/mysql:rw

volumes:
  mysql:
